baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: 
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: about
          url: /
          weight: 2
        - name: papers
          url: papers/
          weight: 3
        - name: news
          url: news/
          weight: 3
  

params:
    description:  "I am a Ph.D. student at the NLP research lab, in the Computer Science Faculty at the Technion, under the supervision of <a href='https://belinkov.com/' style='color: #0066cc; text-decoration: underline; font-weight: bold;'>Yonatan Belinkov</a>. My research focuses on the interpretability of large language models.\n\n\n I enjoy meeting new people—feel free to reach out to me!"
    author: Tal haklay
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tal Haklay
          subtitle: "I am a Ph.D. student at the NLP research lab, in the Computer Science Faculty at the Technion, under the supervision of <a href='https://belinkov.com/' style='color: #0066cc; text-decoration: underline; font-weight: bold;'>Yonatan Belinkov</a>. My research focuses on the interpretability of large language modelsmance and reliability.\n\n\n I enjoy meeting new people—feel free to reach out to me!"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            #- name: Papers
            #  url: papers/
            #- name: News
            #  url: news/


    socialIcons:
        - name: Email
          url: mailto:tal.ha@campus.technion.ac.il
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=oRPEEWIAAAAJ&hl=iw&oi=ao
        - name: Twitter
          url: https://x.com/tal_haklay
        - name: GitHub
          url: https://github.com/TalHaklay

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Tal Haklay
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2